//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public double PricePerDay { get; set; }
        public double PriceExtra { get; set; }
        public System.DateTime Year { get; set; }
        public bool IsManual { get; set; }
        public short KM { get; set; }
        public string Picture { get; set; }
        public bool IsCarReadyToRent { get; set; }
        public bool IsCarAvailable { get; set; }
        public short CarNum { get; set; }
        public string BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
